### PR TITLE
Geometry fixes

### PR DESCRIPTION
**Pull request by reskume**
Fixes lots of issues with geometries: mainly self-intersections, duplicates, typos.

### CODE REVIEW

**Comment by llauner** [comment]
Hi
How did you fix these ? manually ? were they fixes not done by the tool ?
Regards,
Ludovic

**Comment by reskume** [comment]
I refactored our parser (https://github.com/openAIP/openaip-openair-parser)
to also output openair formatted strings. This helped in fixing airspaces
that had duplicates. The self-intersections were all fixed manually to not
loose the original openair text if there were arcs defined in it. The
parser can actuall fix most geometry issues BUT it will always create
polygons in the background. This means that if an airspace with an arc
definition is fixed, the returned openair will only contain DP definitions
instead of the original arc definition.

Ludovic ***@***.***> schrieb am Di., 5. Juli 2022, 20:11:

**Comment by llauner** [comment]
Hi
Could you rebase your branch onto master ? It looks like there are conflicts right now...
Thanks

**Comment by reskume** [comment]
Merged upstream changes

**Comment by llauner** [comment]
@jpcotto 
Why did you close the PR ??

**Pull request merged**
