### PR TITLE
Add airspace frequency information when available

### PR DESCRIPTION
**Pull request by llauner**
As requested in: #7
Added airspace radio frequency where available.

### CODE REVIEW

**Comment by lordfolken** [comment]
This works really nicely now:
2022-09-20-202956_958x527_scrot

**Review by lordfolken — APPROVED** [review]
In general ok. I cannot vouch for correctness of the data. 
The only question, is whether it still makes sense to keep the frequency in the title. 
I guess for a transition phase this is ok.

**Comment by llauner** [comment]
@lordfolken yes…I wasn’t sure whether the AF information was being used in other software such as the LX90xx or SeeYou mobile, SeeYou Navigator, …
Let’s keep the I go in the title as well and we’ll delete it when we are sure that it is no longer needed.

**Comment by jpcotto** [comment]
Hi 
There are no mistakes in frequencies that were already registred.

**Pull request merged**
