### PR TITLE
Remove RMZ Grenoble le Versoud which should not be anymore active.

### PR DESCRIPTION
**Pull request by snip**

### CODE REVIEW

**Comment by llauner** [comment]
Looks like the DMZ has been made active until the end of the year. I suspect it will re-activated again next year, so let's keep it for now...
https://www.sia.aviation-civile.gouv.fr/documents/supaip/aip/id/6
What do you think ?

**Comment by snip** [comment]
Where is it activated until the end of the year? I can only see 15th of June 2023:

image

**Comment by snip** [comment]
Ho ok i see:

image


image

So simple :(

**Comment by llauner** [comment]
> Ho ok i see:
> So simple :(

Yes, it's very confusing that the pdf does not include the modified dates...

**Pull request closed without merging**
